### PR TITLE
Fix stack overflow with Rust generated code in debug builds on Windows

### LINKED ISSUE #133: Stack overflow on Windows in Rust Debug Builds
Due to the inlining the generated structures tend to become rather big (the gallery for example ~13kb with the ugly style), which on debug builds with Rust on Windows tends to result in a bunch of copies of said struct. That can lead to the process running out of stack space.

### PR DESCRIPTION
**Pull request by tronical**
On Windows the default stack size is less than on Linux/macOS and
therefore an issues surfaces that is however operating system agnostic:

Due to inlining we generate quite big inner components with many fields.
Their field offsets are accumulated in the separate FIELD_OFFSETS
struct. The access pattern typically looks like this:

    Self::FIELD_OFFSETS.some_field.apply_pin(...)

This is destructed into at least two smaller operations, fetching
some_field and then calling apply_pin with that field as self parameter.

In Rust debug builds the first operation, unfortunately, ends up making
a full copy of Self::FIELD_OFFSETS into a temporary variable on the
stack. Unfortunately also that stack space isn't reused, so every access
results in a new stack allocation to hold all of the FIELD_OFFSETS
structure (~5kb in the printer demo).

With so many accesses to that in the generated code, we run out of stack
space already in the new() function, in item_tree() as well as in the
Drop impl that also accesses all field offsets.

This patch applies the following workaround that does the trick. The
above expression is replaced with

    {
        let field = &Self::FIELD_OFFSETS.some_field;
        *field
    }.apply_pin(...)

Fixes #133

### CODE REVIEW

File: sixtyfps_compiler/generator/rust.rs [hunk 1]
```diff
@@ -1951,3 +1959,21 @@ fn compile_path(path: &Path, component: &Rc<Component>) -> TokenStream {
...
+// binding initialization functions isn't re-used and with large generated inner
+// components ends up large amounts of stack space.
+fn access_component_field_offset(component_id: &Ident, field: &Ident) -> TokenStream {
+    quote!({
+        let field = &#component_id::FIELD_OFFSETS.#field;
+        *field
+    })
+}
+
+fn access_self_field_offset(field: &Ident) -> TokenStream {
```
Comment (ogoffart) [inline sixtyfps_compiler/generator/rust.rs:1974]: is that not the same as `access_component_field_offset(quote!(Self), field)` ?
either just make access_component_field_offset take a TokenStream instead.  or replace quote by format_indent or something

File: sixtyfps_compiler/generator/rust.rs [hunk 2]
```diff
@@ -1951,3 +1959,21 @@ fn compile_path(path: &Path, component: &Rc<Component>) -> TokenStream {
         }
     }
 }
+
+// In Rust debug builds, accessing the member of the FIELD_OFFSETS ends up copying the
+// entire FIELD_OFFSETS into a new stack allocation, which with large property
+// binding initialization functions isn't re-used and with large generated inner
+// components ends up large amounts of stack space.
```
Comment (ogoffart) [inline sixtyfps_compiler/generator/rust.rs:1966]: maybe reference the issue number (133)

**Review by ogoffart — COMMENTED** [review]
Nice to see this fixed! :+1:

Does that mean we should revert 51836a945723f7fa20729764d7c9ab736a0554c6 ?

File: sixtyfps_compiler/generator/rust.rs (hunk 1 above)
Comment (tronical) [reply sixtyfps_compiler/generator/rust.rs:1974]: Good idea! Done.

File: sixtyfps_compiler/generator/rust.rs (hunk 2 above)
Comment (tronical) [reply sixtyfps_compiler/generator/rust.rs]: Good idea, too :)

**Comment by tronical** [comment]
> Does that mean we should revert [51836a9](https://github.com/sixtyfpsui/sixtyfps/commit/51836a945723f7fa20729764d7c9ab736a0554c6) ?

I don't think that we have to, but it makes the generated code a little easier, so I'm in favour of reverting it.

**Review by ogoffart — APPROVED** [review]

File: sixtyfps_compiler/generator/rust.rs [hunk 3]
```diff
@@ -1951,3 +1959,21 @@ fn compile_path(path: &Path, component: &Rc<Component>) -> TokenStream {
...
+fn access_component_field_offset(component_id: &Ident, field: &Ident) -> TokenStream {
+    quote!({
+        let field = &#component_id::FIELD_OFFSETS.#field;
```
[the remark this answers is not in the document]
Comment (tronical) [reply sixtyfps_compiler/generator/rust.rs]: You're right, that works as well - I tried. Nice, that makes it even simpler. I'll keep the function to encapsulate this around though - as a way to anchor the comment. Hopefully in a future release of Rust we can remove this again.
