### PR TITLE
Fix panic when calling focus() on a repeated element

### LINKED ISSUE #422: Panic when calling `focus()` on conditional element
Noticed this when upgrading cargo-ui, the following test-case causes a panic due to out-of-bounds item-tree access:

```
export Test := Window {
    if (true): combo := FocusScope {
        TouchArea {
            clicked => {
                combo.focus();
            }
        }
    }
}
```

This is triggered in cargo-ui through the use of the ComboBox in the package selection, that itself is a conditional focus scope.

### PR DESCRIPTION
**Pull request by tronical**
When trying to reference an instance of a repeated item, for use with
ItemRc or VRef<Item>, the item_index (or id) of the ElementRc is not
directly what we want.

For the Rust and C++ code generators, the self/_self already refers
correctly to the repeated instance, but item_index must be zero to refer
to the root.

For the interpreter the self equivalent is the
local_context.component_instance is already the repeated instance that
we can use, and we're just looking for the root element of that, in
order to create the ItemRc/VRef.

Fixes #422

### CODE REVIEW

**Comment by ogoffart** [comment]
Does that work with several level of repeater?

eg, the example slightly modified: 

```
export TestCase := Window {
    width: 100phx;
    height: 100phx;

    property<bool> combo_has_focus;

    if (true): combo := FocusScope {
        if (true): TouchArea {
            clicked => {
                combo.focus();
                root.combo_has_focus = combo.has-focus;
            }
        }
    }
}
```

File: sixtyfps_compiler/generator/rust.rs [hunk 1]
```diff
@@ -1247,7 +1247,13 @@ fn compile_expression(expr: &Expression, component: &Rc<Component>) -> TokenStre
                     if let Expression::ElementReference(focus_item) = &arguments[0] {
                         let focus_item = focus_item.upgrade().unwrap();
                         let focus_item = focus_item.borrow();
-                        let item_index = focus_item.item_index.get().unwrap();
+                        let item_index = if focus_item.repeated.is_some() {
+                            // We want the repeated instance itself; _self already points to it, and the root element
```
Comment (ogoffart) [inline sixtyfps_compiler/generator/rust.rs:1251]: i'm concern that _self does not always points to it as it could be a deeper instance.

**Comment by ogoffart** [comment]
I'm wondering: what does the focus_item in `Expression::ElementReference(focus_item)` points to, the "inner" or the "outer" ?
I believe this should already points to the "inner" element. If not, i think the bug is there, and we should not be trying to fix it in the codegen, but rather when creating the ElementReference

File: sixtyfps_compiler/generator/rust.rs (hunk 1 above)
Comment (tronical) [reply sixtyfps_compiler/generator/rust.rs:1251]: You're right, `self` is incorrect in this nested case.

**Comment by tronical** [comment]
You're right, the real bug seems to be that `focus_item` is pointing to the outer element. That would probably make it work right away in the interpreter and the C++/Rust code generators still need code to traverse "up" from `self` if needed - similar to `access_member`.

File: sixtyfps_compiler/generator/cpp.rs [hunk 2]
```diff
@@ -1413,6 +1413,34 @@ fn access_named_reference(
...
+                .unwrap()
+                .borrow()
+                .enclosing_component
+                .upgrade()
+                .unwrap(),
+            &format!("{}->parent", component_cpp),
+        )
+        .to_string()
+        .into()
+    }
```
Comment (tronical) [inline sixtyfps_compiler/generator/cpp.rs:1441]: This doesn't *have* to be a recursion, I could also write it as a simple loop. Do you have a preference?

File: sixtyfps_compiler/passes/repeater_component.rs [hunk 3]
```diff
@@ -93,4 +93,18 @@ fn adjust_references(comp: &Rc<Component>) {
             };
         }
     });
+    // Transform any references to the repeated element to refer to the root of each instance.
+    visit_all_expressions(comp, |expr, _| {
```
Comment (tronical) [inline sixtyfps_compiler/passes/repeater_component.rs:97]: This is quite "aggressive" and I'm not entirely certain if this needs any additional checks ("access only from inside?").

File: sixtyfps_compiler/expression_tree.rs [hunk 4]
```diff
@@ -776,6 +776,12 @@ impl Expression {
         self.visit(|e| e.visit_recursive(visitor));
     }
 
+    /// Visit itself and each sub expression recursively
```
Comment (ogoffart) [inline sixtyfps_compiler/expression_tree.rs:779]: i really wish there was some way to not have to duplicate everything for mut and non mut

File: sixtyfps_compiler/generator/cpp.rs (hunk 2 above)
Comment (ogoffart) [reply sixtyfps_compiler/generator/cpp.rs:1441]: i don't have a preference.

**Comment by tronical** [comment]
I've implemented a different approach now that tries to solve this before the code gen. I have the sinking feeling that I might be missing something though.

File: sixtyfps_compiler/passes/repeater_component.rs (hunk 3 above)
Comment (ogoffart) [reply sixtyfps_compiler/passes/repeater_component.rs:97]: A few line earlier, we do something similar.  so i guess that's ok.

**Review by ogoffart — APPROVED** [review]

**Comment by tronical** [comment]
Thx :)
