### PR TITLE
Produce an error message when using if or for in grid layouts

### LINKED ISSUE #349: `for` within a GridLayout produces invalid code, or panics
Steps to reproduce:

```
#!/bin/sh
cargo new bug 
cd bug
echo 'sixtyfps = "0.1.0"' >> Cargo.toml
cat > src/main.rs <<- EOM
fn main() {
    MainWindow::new().run();
}

sixtyfps::sixtyfps! {
    MainWindow := Window {
        //Image {
        //    source: @image-url("icons/bus.png");
        //}
        GridLayout {
            for img in [
                @image-url("icons/bus.png"),
                @image-url("icons/bus.png"),
                @image-url("icons/bus.png"),
                @image-url("icons/bus.png"),
                @image-url("icons/bus.png")
            ] : Image {
                source: img;
            }
        }
    }
}
EOM
cargo run --release

# to ensure that creating single image will work, can be omitted
curl -O https://sixtyfps.io/blog/memory-game-tutorial/icons.zip && unzip icons.zip
```
gives an error:
```
error[E0609]: no field `image_3` on type `InnerMainWindowFieldsOffsets`
  --> src/main.rs:5:1
   |
5  | / sixtyfps::sixtyfps! {
6  | |     MainWindow := Window {
7  | |         //Image {
8  | |         //    source: @image-url("icons/bus.png");
...  |
21 | |     }
22 | | }
   | |_^ unknown field
   |
   = note: available fields are: `root_1`, `gridlayout_2`, `gridlayout_2_layout_cache_h`, `gridlayout_2_layout_cache_v`, `gridlayout_2_layoutinfo_h` ... and 7 others
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by tronical**
An early error is better than a build error at compile time of generated code.

Fixes #349

### CODE REVIEW

File: sixtyfps_compiler/passes/lower_layout.rs [hunk 1]
```diff
@@ -200,6 +200,14 @@ impl GridLayout {
 
         let index = self.elems.len();
         if let Some(layout_item) = create_layout_item(item_element, diag) {
+            if layout_item.repeater_index.is_some() {
+                diag.push_error(
+                    format!("if or for expressions are not currently supported in grid layouts"),
```
Comment (ogoffart) [inline sixtyfps_compiler/passes/lower_layout.rs:205]:
```suggestion
                    format!("'if' or 'for' expressions are not currently supported in grid layouts"),
```

**Review by ogoffart — APPROVED** [review]

**Comment by ogoffart** [comment]
That's #349

**Comment by tronical** [comment]
> That's #349

Ahh, thanks!
